spring:
  application:
    name: Disaster Alerts

  docker:
    compose:
      file: compose-test.yaml

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/disasterdb
    username: user
    password: pass

#  liquibase:
#    change-log: db/changelog-test.yaml
#    contexts: test

server:
  port: 8082

openweathermap:
  api:
    key: 3261c3b28f5aed55fcca580f4d7744d0
    url: https://api.openweathermap.org/data/2.5/weather

twilio:
  test:
    account.sid: ${TEST_TWILIO_ACCOUNT_SID}
    auth.token: $(TEST_TWILIO_AUTH_TOKEN}
    phone.number: ${TEST_TWILIO_PHONE_NUMBER}