spring:
  main:
    banner-mode: log

  profiles:
    active: dev
    include: test

  mail:
    host: smtp.gmail.com
    port: 587
    username: disaster.alert1@gmail.com
    password: ihrbtliplvclxosl
#    username: ${DISASTER_EMAIL_ACCOUNT}
#    password: ${DISASTER_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

twilio:
  account.sid: ${TWILIO_ACCOUNT_SID}
  auth.token: ${TWILIO_AUTH_TOKEN}
  phone.number: ${TWILIO_PHONE_NUMBER}
  test:
    account.sid: ${TWILIO_TEST_ACCOUNT_SID}
    auth.token: ${TWILIO_TEST_AUTH_TOKEN}

day.sms.limit: ${DAY_SMS_LIMIT}